plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.github.davidmc24.gradle.plugin.avro' version '1.9.1'
}

group = 'com.nik.kafka'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
	maven { url 'https://packages.confluent.io/maven/' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-kafka'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	runtimeOnly 'org.postgresql:postgresql'

	// Avro & Schema Registry - exclude conflicting swagger deps
	implementation('io.confluent:kafka-avro-serializer:7.6.1') {
		exclude group: 'io.swagger.core.v3', module: 'swagger-annotations'
	}
	implementation('io.confluent:kafka-schema-registry-client:7.6.1') {
		exclude group: 'io.swagger.core.v3', module: 'swagger-annotations'
	}

	// Avro
	implementation 'org.apache.avro:avro:1.11.3'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// MapStruct
	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	// MapStruct + Lombok together
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-kafka-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.0'
}

// Avro code generation
avro {
	stringType = 'String'
	fieldVisibility = 'PRIVATE'
}

sourceSets.main.java.srcDirs += ["$buildDir/generated-main-avro-java"]

tasks.named('test') {
	useJUnitPlatform()
}
